### ISSUE TITLE
Guard misses installed keys specified with "0x"

### ISSUE THREAD

**Issue by whiteley** [chef-cookbooks/apt#137]
In the repository provider, `install_key_from_keyserver` will accept a key starting with "0x" and install it successfully with the `apt-key` command but the logic in the `not_if` guard will fail causing it to be installed on every Chef run.
- Should the repository resource validate the attribute to not contain "0x"?
- Should "0x" be stripped from the string before the `end_with?` check?

**Comment by thommay** [comment]
@whiteley can you provide the output of `apt-key finger`in this case and also your `apt_repository` block please?

**Comment by whiteley** [comment]
I was able to reproduce this with the default test-kitchen setup in https://github.com/phlipper/chef-percona and created a gist which shows what I was trying to describe.

https://gist.github.com/whiteley/6ddc1d00b4560d0c46de

If you look at line 6 in `apt_137.out` you see that it's trying to match the correct key but the `0x` breaks the `end_with?` check.

**Comment by whiteley** [comment]
@thommay did you still need more info from me on this?

**Comment by tas50** [comment]
We've removed the apt_update and apt_repository resources from this cookbook as they were merged into core chef. I'm going to close this issue out now. If you think it's still valid against a new chef-client release please open it up against the chef/chef repo so we can work on it where the code now resides.
