### ISSUE TITLE
Non apt based systems attempting to install apt-transport-https

### ISSUE THREAD

**Issue by trilitheus** [chef-cookbooks/apt#168]
Commit 818ae9f added install of apt-transport-https with no guard.  This cookbooks default recipe is included by many other cookbooks and this breaks the chef run when pulling in version 2.9.1 of this cookbook.

**Comment by someara** [comment]
Hello!

I added a guard to the package resource in v2.9.2

However, I'm not entirely sure this is a bug....  The apt cookbook shouldn't be applied to non-apt based systems. Is the cookbook that depends on this a community cookbook? or internal. I'd like to fix this upstream.

-s

**Comment by trilitheus** [comment]
This is my 'wrapper' cookbook pulling in dependencies.  I only run Centos at the moment so am not calling this myself.  I've just checked through my Berksfile.lock to see where else the apt dependency is but going through those I can't see where the inclusion of the apt::default recipe is being called.  Will update further if I track it down

**Comment by tas50** [comment]
The entire default  recipe has a guard around on master right now.  That change will be shipping in 3.0. We've also added testing to ensure that RHEL 7 doesn't get any changes when the default recipe is applied.
