### ISSUE TITLE
Deprecate the use of short key IDs

### ISSUE THREAD

**Issue by whiteley** [chef-cookbooks/apt#172]
Some discussion here: http://security.stackexchange.com/questions/74009/what-is-an-openpgp-key-id-collision

With a link to the key take away at: http://tools.ietf.org/html/rfc4880#section-3.3

The long IDs already work fin but it would be nice to start throwing a warning message when the `apt_repository` resource is used with a short ID.

**Comment by tas50** [comment]
We've removed the apt_update and apt_repository resources from this cookbook as they were merged into core chef. I'm going to close this issue out now. If you think it's still valid against a new chef-client release please open it up against the chef/chef repo so we can work on it where the code now resides.
