### ISSUE TITLE
:repo_name attribute for apt_repository LWRP not used

### ISSUE THREAD

**Issue by poliva83** [chef-cookbooks/apt#173]
The name attribute `:repo_name` defined in [repository](https://github.com/chef-cookbooks/apt/blob/master/resources/repository.rb#L44) resource is not actually used in the provider class. I found this confusing since the attribute is documented in the README.md.

**Comment by tas50** [comment]
While true the name property isn't used there's no real reason to remove it's the name property. If you'd like to open a PR to update the readme, we'd be happy to clarify things there.
