### ISSUE TITLE
apt_repository before apt causes unexpected behaviour

### ISSUE THREAD

**Issue by schocco** [chef-cookbooks/apt#177]
Adding a repository via `apt_repository` triggers an apt-get update to be executed which only includes the newly added source list.  The documentation could be misleading as it states that `execute[apt-get-update]` is triggered immediately. An additional note in the documentation might be helpful to point out the implications of the partial update that is triggered by `apt_repository`. It is still necessary to add `apt` to the first position of the run-list when adding repositories.

This partial update touches `/var/lib/apt/periodic/update-success-stamp` and `/var/lib/apt/periodic/update-stamp`. As a result `helpers.rb/apt_up_to_date?` returns true even though only a partial update has been done and the rest of the index might be outdated.  
In some cases this can lead to unexpected issues, as demonstrated in the example below:

``` ruby
apt_repository "nodejs" do
  uri "https://deb.nodesource.com/node"
  distribution node['lsb']['codename']
  components ["main"]
  key "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
end

include_recipe 'apt'

package nginx
package nodejs
```

The example above might fail due to an outdated index which won't be updated. Apt-get might attempt to install a package version which no longer exists (currently the case on ec2 ubuntu 14.04 instances).

**Comment by tas50** [comment]
This is probably something that we should clarify with an update to the readme explaining the update behavior. If you could put that together in a PR I'd be more than happy to merge it.

**Comment by tas50** [comment]
We've removed the apt_update and apt_repository resources from this cookbook as they were merged into core chef. I'm going to close this issue out now. If you think it's still valid against a new chef-client release please open it up against the chef/chef repo so we can work on it where the code now resides.
