### ISSUE TITLE
Adding key and keyserver to existing repo doesn't work

### ISSUE THREAD

**Issue by pauldraper** [chef-cookbooks/apt#180]
If the repository has already been added in an early invocation of chef-client, adding a key to the resource does not work.

The repository must first be removed and then chef must be re-run for the key to be added.

**Comment by tas50** [comment]
We've removed the apt_update and apt_repository resources from this cookbook as they were merged into core chef. I'm going to close this issue out now. If you think it's still valid against a new chef-client release please open it up against the chef/chef repo so we can work on it where the code now resides.
