### ISSUE TITLE
File files/default/15update-stamp does not exist for cookbook apt

### ISSUE THREAD

**Issue by avecchio** [chef-cookbooks/apt#184]

**Comment by thommay** [comment]
Please reopen with some details as to what platform, cookbook version and chef version you're running

**Comment by avecchio** [comment]
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2

apt-2.9.2

OSX Yosemite

**Comment by tas50** [comment]
This will be resolved with https://github.com/chef-cookbooks/apt/pull/186

**Comment by avecchio** [comment]
Fantastic. I am sorry I was not able to pinpoint more of the issue. I am only a novice at chef systems. I just figured it should be known since this seems to be a common recipe. I will go ahead and close the issue then.

**Comment by tas50** [comment]
I'm actually amazed that were hadn't had an issue with this earlier.  I added testing so we make sure we don't create anything apt in the future on non-Debian based systems.  Thanks for reporting this.
