### ISSUE TITLE
apt_repository should honour the components values given, regardless of whether it's a ppa repository

### ISSUE THREAD

**Issue by eric-tucker** [chef-cookbooks/apt#200]
https://github.com/chef-cookbooks/apt/blob/master/providers/repository.rb#L209

I have no idea what the rationale behind this might be, but this does not work with, for example, the cinnamon repository for 14.04 LTS located at ppa:moorkai/cinnamon

I spent over an hour trying to figure out why the apt_repository resource would not honour the settings I was providing for components.

Ignoring and overriding user input seems like a bad idea in my opinion.

**Comment by eric-tucker** [comment]
Any updates here folks?  Having to manually run installs for countless repositories because apt_repository isn't honouring my components value is very tedious.

**Comment by tas50** [comment]
We've removed the apt_update and apt_repository resources from this cookbook as they were merged into core chef. I'm going to close this issue out now. If you think it's still valid against a new chef-client release please open it up against the chef/chef repo so we can work on it where the code now resides.
