### ISSUE TITLE
Issue with v3.0.0 execute[apt-get update]

### ISSUE THREAD

**Issue by puckel** [chef-cookbooks/apt#201]
Hi,

Since v3.0.0 release, I can't run chefspec tests, I've the following error :

> Failure/Error: runner.converge(described_recipe)
>       Chef::Exceptions::ResourceNotFound:
>         resource apt_repository[dotdeb] is configured to notify resource execute[apt-get update] with action run, but execute[apt-get update] cannot be found in the resource collection. apt_repository[dotdeb] is defined in /var/folders/9l/z3zw1q611v11bh7xxx2n9vvh0000gn/T/d20160323-94631-148blpg/cookbooks/front/recipes/apt.rb:44:in `from_file'

My recipe :
>     include_recipe 'apt::default'
>     apt_repository 'dotdeb' do
>       uri 'http://packages.dotdeb.org'
>       distribution jessie
>       components all
>       action :add
>       notifies :run, 'execute[apt-get update]', :immediately
>     end

No problem with v2.9.2.

Any ideas ?

Thanks

**Comment by puckel** [comment]
Hi. Do you need more information ? Thanks

**Comment by thommay** [comment]
fixed in master, should be released soon. Thanks for your report!

**Comment by puckel** [comment]
Thanks

**Comment by puckel** [comment]
Hi,

Do you plan a new release soon ?

Thanks

**Comment by tas50** [comment]
4.0 is out today
