### ISSUE TITLE
Add a warning on the README that https://github.com/chef/chef/pull/4782 supersedes this cookbook's `apt_repository` LWRP

### ISSUE THREAD

**Issue by wk8** [chef-cookbooks/apt#204]

**Comment by jeremymv2** [comment]
@thommay Thoughts on users who are consuming this cookbook and using chef-client that has the apt_repository Resource built-in?  When that is the case, they receive an exception:  `superclass mismatch for class AptRepository`

**Comment by grimm26** [comment]
It only affects me because it broke zap https://github.com/nvwls/zap/issues/33

**Comment by poliva83** [comment]
I was hitting `superclass mismatch for class AptRepository` because my rake task was triggering a chef-client run via Chef:Client object. I switched to use a Chef::Application::Client object instead and I no longer have this issue (now I see a warning instead during compile phase).

**Comment by tas50** [comment]
@jeremymv2 were you seeing that mismatch in the 3.X release or on master?

**Comment by grimm26** [comment]
@tas50 I get it with the new 4.0.0 release.
```
....
 Synchronizing Cookbooks:
         - apt (4.0.0)
         - compat_resource (12.10.4)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       [2016-06-02T21:12:33+00:00] WARN: Chef::Provider::AptRepository already exists!  Cannot create deprecation class for LWRP provider apt_repository from cookbook apt
       [2016-06-02T21:12:33+00:00] WARN: AptRepository already exists!  Deprecation class overwrites Custom resource apt_repository from cookbook apt
....

**Comment by tas50** [comment]
If someone wants to open a PR with a small note that explains how this related to the built in resource I'd be more than happy to merge that in.

**Comment by tas50** [comment]
We've removed the apt_update and apt_repository resources from this cookbook as they were merged into core chef. I'm going to close this issue out now. If you think it's still valid against a new chef-client release please open it up against the chef/chef repo so we can work on it where the code now resides.
