### ISSUE TITLE
Port apt_preference to chef/chef

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/apt#215]
apt_update and apt_repository have been ported into the core chef client. We should do the same with apt_preference and eliminate the need for this cookbook.

**Comment by cheeseplus** [comment]
Any update on this front @tas50?

**Comment by tas50** [comment]
I'm going to close this out here since there's an inactive PR sitting on chef/chef for this. We should track it there

**Comment by tas50** [comment]
This will ship with Chef 13.3
